// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package eventbridge

import (
	context "context"

	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"

	mock "github.com/stretchr/testify/mock"
)

// MockAsgPublisher is an autogenerated mock type for the AsgPublisher type
type MockAsgPublisher struct {
	mock.Mock
}

// PublishAsgGroups provides a mock function with given fields: ctx, asgs
func (_m *MockAsgPublisher) PublishAsgGroups(ctx context.Context, asgs []*autoscaling.Group) error {
	ret := _m.Called(ctx, asgs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*autoscaling.Group) error); ok {
		r0 = rf(ctx, asgs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
