// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"

	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// AwsAutoScaling is an autogenerated mock type for the awsAutoScaling type
type AwsAutoScaling struct {
	mock.Mock
}

// DescribeAutoScalingGroupsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AwsAutoScaling) DescribeAutoScalingGroupsPagesWithContext(_a0 context.Context, _a1 *autoscaling.DescribeAutoScalingGroupsInput, _a2 func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeTagsPagesWithContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AwsAutoScaling) DescribeTagsPagesWithContext(_a0 context.Context, _a1 *autoscaling.DescribeTagsInput, _a2 func(*autoscaling.DescribeTagsOutput, bool) bool, _a3 ...request.Option) error {
	_va := make([]interface{}, len(_a3))
	for _i := range _a3 {
		_va[_i] = _a3[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1, _a2)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeTagsInput, func(*autoscaling.DescribeTagsOutput, bool) bool, ...request.Option) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
