// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package autoscaling

import mock "github.com/stretchr/testify/mock"

// mockAwsAutoScaling is an autogenerated mock type for the awsAutoScaling type
type mockAwsAutoScaling struct {
	mock.Mock
}

// DescribeAutoScalingGroupsPages provides a mock function with given fields: input, fn
func (_m *mockAwsAutoScaling) DescribeAutoScalingGroupsPages(input *autoscaling.DescribeAutoScalingGroupsInput, fn func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool) error {
	ret := _m.Called(input, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*autoscaling.DescribeAutoScalingGroupsInput, func(*autoscaling.DescribeAutoScalingGroupsOutput, bool) bool) error); ok {
		r0 = rf(input, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DescribeTagsPages provides a mock function with given fields: input, fn
func (_m *mockAwsAutoScaling) DescribeTagsPages(input *autoscaling.DescribeTagsInput, fn func(*autoscaling.DescribeTagsOutput, bool) bool) error {
	ret := _m.Called(input, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*autoscaling.DescribeTagsInput, func(*autoscaling.DescribeTagsOutput, bool) bool) error); ok {
		r0 = rf(input, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
